<style>
    .favorites-action:before {
        content: "\e606";       /* This is not ideal, but it's good enough for now in a hackathon. */
    }
</style>
<?php

// @codingStandardsIgnoreFile

?>
<?php /** @var $this \Hackathon\AdminFavorites\Block\ToolbarEntry */ ?>
<?php
$isFavorite = $block->isCurrentPageFavorite();
?>
<div class="notifications-wrapper admin__action-dropdown-wrap"
    data-mage-init='{"toolbarEntry": {}}'
    data-favorites-key="">
    <?php if ($isFavorite) : ?>
        <a
            class="notifications-action admin__action-dropdown"
            href="/"
            title="<?php /* @escapeNotVerified */ echo __('Click to remove Favorite'); ?>">
        </a>
    <?php else : ?>
        <a
            class="notifications-action favorites-action admin__action-dropdown"
            href="/"
            title="<?php /* @escapeNotVerified */ echo __('Click to add Favorite'); ?>">
        </a>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require(['jquery','adminFavoritesToolbarEntry'],function($){
        $(window).load(function() {
        });
    });
</script>