<style>
    .favorites-wrapper {
        float: right;
        z-index: 401;
    }
    .favorites-menu-row {
        width: 650px;
        list-style: none none;
        line-height: 2;
    }
    .favorites-menu-row ul li {
        list-style: none none;
    }
    .favorites-item {
        font-size: 10px;
        line-height: 2;
        margin: 3px;
    }
    .item-favorites-link:hover{
        background-color: #e0f6fe;
        text-decoration: none;
    }
    .favorites-wrapper-dropdown{
        padding-top:10px;
        padding-bottom: 10px;
        padding-right: 15px;
        padding-left:15px;
    }
</style>
<?php

// @codingStandardsIgnoreFile

?>
<?php /** @var $this \Hackathon\AdminFavorites\Block\ToolbarEntry */ ?>
<div
    id="favorites-wrapper-id"
    class="favorites-wrapper admin__action-dropdown-wrap"
    data-mage-init='{"toolbarEntry": {}}'
    data-favorites-key=""
    data-increment-page-viewed-url="<?php echo $this->getIncrementUrl();?>">
    <a
        href="#"
        class="favorites-action admin__action-dropdown"
        title="<?php /* @escapeNotVerified */ echo __('Click to View Favorites'); ?>"
        data-mage-init='{"dropdown":{}}'
        data-toggle="dropdown"
    >
    </a>
    <div class="favorites-wrapper-dropdown admin__action-dropdown-menu">
            <button id="adminfavorites_remove" class="hidden" type="button" title="Remove this page from favorites">
                <span>Remove</span>
            </button>
            <button id="adminfavorites_add" class="hidden" type="button" title="Add this page to favorites">
                <span>Add</span>
            </button>

        <ul
            class="favorites-menu-row"
            data-mark-as-read-url="">
            <li class="column col-l-4">
                <ul role="menu">
                    <li data-ui-id="menu-magento-reports-report-marketing" class="item-report-marketing  parent  level-1" role="menu-item">
                        <strong class="submenu-group-title" role="presentation">
                            <span>Favorites</span>
                        </strong>
                        <div class="submenu">
                            <ul id="favorites-menu" role="menu">
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="column col-l-4">
                <ul role="menu">
                    <li data-ui-id="menu-magento-reports-report-marketing" class="item-report-marketing  parent  level-1" role="menu-item">
                        <strong class="submenu-group-title" role="presentation">
                            <span>Recently Viewed</span>
                        </strong>
                        <div class="submenu">
                            <ul id="recently-viewed-menu" role="menu">
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="column col-l-4">
                <ul role="menu">
                    <li data-ui-id="menu-magento-reports-report-marketing" class="item-report-marketing  parent  level-1" role="menu-item">
                        <strong class="submenu-group-title" role="presentation">
                            <span>Mostly Viewed</span>
                        </strong>
                        <div class="submenu">
                            <ul id="mostly-viewed-menu" role="menu">
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<script type="text/javascript">
    var currentPageKey = '<?php echo $this->getCurrentPageKey(); ?>';
    var getFavesUrl = '<?php echo $this->getGetFavoritesUrl(); ?>';
    var addFavoriteUrl = '<?php echo $this->getAddFavoriteUrl(); ?>//';
    var removeFavoriteUrl = '<?php echo $this->getRemoveFavoriteUrl(); ?>//';

    var getFavesData = {form_key: window.FORM_KEY};

    require(['jquery','adminFavoritesToolbarEntry'],function($){
        $(window).load(function() {
        });
    });
</script>